platform :ios, '7.0'

target 'Smile TouchID' do

#pod 'SmileTouchID', :path => '~/Documents/my_practice/security/SmileTouchID'
pod 'SmileTouchID', :git => 'https://github.com/liu044100/SmileTouchID.git'

end

target 'TouchIDTests' do

end

