# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Smile TouchID' do

pod 'SmileTouchID', :git => 'https://github.com/liu044100/SmileTouchID.git'

end

target 'TouchIDTests' do

end

